import { cn } from "@/lib/utils";
import { getThemeStyles, type DesignSystem, type ThemeData } from "@/lib/designSystem";
import { AnimatedSection } from "./AnimatedSection";

interface Testimonial {
  name: string;
  role: string;
  content: string;
}

interface TestimonialsProps {
  testimonials?: Testimonial[];
  theme: ThemeData;
  design: DesignSystem;
}

export function Testimonials({ testimonials = [], theme, design }: TestimonialsProps) {
  const styles = getThemeStyles(theme, design);

  const normalize = (value: any, fallback = "") => {
    if (typeof value !== "string") return fallback;
    const trimmed = value.trim().replace(/\s+/g, " ");
    return trimmed || fallback;
  };

  const safeTestimonials = Array.isArray(testimonials)
    ? testimonials.map((testimonial) => {
        const name = normalize(testimonial?.name, "Anonymous");
        const role = normalize(testimonial?.role, "");
        let content = normalize(testimonial?.content, "");
        if (content.length > 420) {
          content = `${content.slice(0, 420).trim()}…`;
        }
        const initials = name
          .split(" ")
          .filter(Boolean)
          .slice(0, 2)
          .map((word) => word[0].toUpperCase())
          .join("");
        return { name, role, content, initials };
      })
    : [];

  return (
    <AnimatedSection
      id="testimonials"
      animationLevel={design.animationLevel}
      className={cn("overflow-hidden", styles.density.sectionPadding)}
      style={{ color: styles.textColor }}
    >
      <div className="mx-auto max-w-7xl">
        <div className="max-w-2xl space-y-3">
          <p className="text-sm uppercase tracking-[0.28em]" style={{ color: styles.accentColor }}>
            Testimonials
          </p>
          <h2 className="text-3xl font-semibold tracking-tight" style={{ color: styles.textColor }}>
            Early users praise the experience.
          </h2>
          <p className="max-w-2xl leading-8" style={{ color: styles.mutedTextColor }}>
            Social proof pieces are automatically plotted from the audience and product story generated by the AI.
          </p>
        </div>

        <div className={cn("mt-10 grid gap-6 lg:grid-cols-2", styles.density.sectionGap)}>
          {safeTestimonials.length > 0 ? (
            safeTestimonials.map((testimonial, index) => (
              <article key={index} className={cn(styles.cardClass, "p-8")}>
                <div className="mb-5 flex items-center gap-4">
                  <div
                    className={cn("flex h-11 w-11 items-center justify-center text-sm font-semibold", styles.radiusClass)}
                    style={{ backgroundColor: styles.accentColor, color: styles.buttonStyle.color }}
                  >
                    {testimonial.initials}
                  </div>
                  <div>
                    <p className="text-base font-semibold" style={{ color: styles.textColor }}>
                      {testimonial.name}
                    </p>
                    <p className="text-sm" style={{ color: styles.mutedTextColor }}>
                      {testimonial.role}
                    </p>
                  </div>
                </div>
                <p className="leading-7" style={{ color: styles.mutedTextColor }}>
                  “{testimonial.content}”
                </p>
              </article>
            ))
          ) : (
            <article className={cn(styles.cardClass, "p-8 lg:col-span-2")}>
              <p className="text-base leading-7" style={{ color: styles.mutedTextColor }}>
                Customer testimonials will appear here once the AI completes the page generation.
              </p>
            </article>
          )}
        </div>
      </div>
    </AnimatedSection>
  );
}
